pipeline {
    agent any
    environment {
      DOCKER_IMG = 'ankitrazorpay/pipelinedemo:${BUILD_NUMBER}'
      scannerHome = tool 'SonarScanner'
    }
    stages { 
      stage('preparation'){
       steps {
        echo 'cloning repo'
        git branch: 'main', url: 'https://github.com/ankitdas13/node-microservices.git'
       }
      }
      stage('SonarQube Analysis') {
        steps {
          withSonarQubeEnv('SonarScanner') {
            sh "${scannerHome}/bin/sonar-scanner"
          }
        }
       }
      stage('test'){
       steps {
        echo 'running test cases'
        nodejs(nodeJSInstallationName: 'node 18') {
          sh 'npm i -D'
          sh 'npm run test'
        }
       }
      }
      stage('build'){
       steps {
        echo 'building image'
        sh 'docker build -t ankitrazorpay/pipelinedemo:${BUILD_NUMBER} .'
       }
      }
      stage('deploy to dockerhub'){
       steps {
        echo 'building image'
        withCredentials([usernamePassword(credentialsId: 'dockerhubcred', passwordVariable: 'PASSWORD_DOC', usernameVariable: 'USERNAME_DOC')]) {
          sh 'docker login -u ${USERNAME_DOC} -p${PASSWORD_DOC}'
          sh 'docker image push ankitrazorpay/pipelinedemo:${BUILD_NUMBER}'
        }
       }
      }
      stage('cleanup'){
        steps {
          sh 'docker logout' 
        }
      }
    }  
}